import omni.anim.graph.core as ag

skel_root_prim_path: str = "/World/Animations/Rig_Retarget/character"

character = ag.get_character(skel_root_prim_path)

# Postures
# character.set_variable("posture_state", "Head_Idle")
# character.set_variable("posture_state", "Idle")
# character.set_variable("posture_state", "Listening")
character.set_variable("posture_state", "Talking")
# character.set_variable("posture_state", "Attentive")
# character.set_variable("posture_state", "Thinking")

# Gestures
# character.set_variable("gesture_state", "Welcome")
# character.set_variable("gesture_state", "Goodbye")
# character.set_variable("gesture_state", "Attraction_1")
# character.set_variable("gesture_state", "Attraction_2")
# character.set_variable("gesture_state", "Bowing_1")
# character.set_variable("gesture_state", "Bowing_2")
# character.set_variable("gesture_state", "Come_Here_1")
# character.set_variable("gesture_state", "Dont_Understand_1")
# character.set_variable("gesture_state", "Driving_Mime")
# character.set_variable("gesture_state", "Exhausted")
# character.set_variable("gesture_state", "Fistbump_Offer")
# character.set_variable("gesture_state", "No_1")
# character.set_variable("gesture_state", "Nodding_1")
# character.set_variable("gesture_state", "Open_Question_1")
# character.set_variable("gesture_state", "Personal_Statement_1")
# character.set_variable("gesture_state", "Personal_Statement_2")
# character.set_variable("gesture_state", "Phone_Dialing")
# character.set_variable("gesture_state", "Please_Repeat_1")
# character.set_variable("gesture_state", "Please_Repeat_2")
# character.set_variable("gesture_state", "Pointing_Backward_1")
# character.set_variable("gesture_state", "Pointing_Down_1")
# character.set_variable("gesture_state", "Pointing_Down_2")
# character.set_variable("gesture_state", "Pointing_Left_1")
# character.set_variable("gesture_state", "Pointing_Left_2")
# character.set_variable("gesture_state", "Pointing_To_Self_1")
# character.set_variable("gesture_state", "Pointing_To_User_1")
# character.set_variable("gesture_state", "Pointing_To_User_2")
# character.set_variable("gesture_state", "Presenting_Options_1")
# character.set_variable("gesture_state", "Presenting_Options_2")
# character.set_variable("gesture_state", "Pulling_Mime")
# character.set_variable("gesture_state", "Raise_Both_Arms")
# character.set_variable("gesture_state", "Stupid_1")
# character.set_variable("gesture_state", "Success_1")
# character.set_variable("gesture_state", "Tell_Secret")
# character.set_variable("gesture_state", "The_Robot")
# character.set_variable("gesture_state", "Trying_To_See")
# character.set_variable("gesture_state", "Toss")
